# Generated by Django 4.0.4 on 2022-05-13 05:18

from django.db import migrations
import petstagram.auth_app.managers


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='petstagramuser',
            managers=[
                ('objects', petstagram.auth_app.managers.PetstagramUserManager()),
            ],
        ),
    ]
