# Generated by Django 4.0.4 on 2022-05-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_alter_petstagramuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='petstagramuser',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
