# Generated by Django 4.0.4 on 2022-05-13 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0002_alter_pet_date_of_birth_alter_pet_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='petphoto',
            name='tagged_pets',
        ),
        migrations.AddField(
            model_name='petphoto',
            name='tagged_pets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='pets.pet'),
        ),
    ]
